apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  namespace: mem-example
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "200Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    
    # Configure a Pod to Use a ConfigMap
    # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/
    envFrom:
    - configMapRef:
      name: special-config
    # Use ConfigMap-defined environment variables in Pod commands
    env:
      - name: SPECIAL_LEVEL_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: SPECIAL_LEVEL
      - name: SPECIAL_TYPE_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: SPECIAL_TYPE
  
  # Assign Pods to Nodes
  # https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/
  # These sections part must be placed under on the same level to containers
  # 1.
  nodeSelector:
    disktype: ssd
  
  # 2. 
  nodeName: foo-node # schedule pod to specific node
  
  # 3.
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd            
  
  # These containers are run during pod initialization
  # https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-initialization/#create-a-pod-that-has-an-init-container

  initContainers:
  - name: install
    image: busybox:1.28
    command:
    - wget
    - "-O"
    - "/work-dir/index.html"
    - http://info.cern.ch
    volumeMounts:
    - name: workdir
      mountPath: "/work-dir"

  # Configure a Pod to Use a Volume for Storage
    # The volumeMounts part must be placed under the section containers block
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  # The volumes part must be placed under on the same level to the containers block
  volumes:
  - name: redis-storage
    emptyDir: {}

# Configure Liveness, Readiness and Startup Probes
# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
# These blocks must be placed under containers block
    # Define a TCP readiness probe
    readinessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    
    # Define a liveness HTTP request 
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
    
    # Define command execution probe
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5

    # Protect slow starting containers with startup probes
    startupProbe:
      httpGet:
        path: /healthz
        port: liveness-port
      failureThreshold: 30
      periodSeconds: 10